version: '3'
services:
  helloworld:
    build: .
    expose:
      - "8080"
      - "8081"
    links:
      - graphite
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    volumes:
      - graphite_data:/opt/graphite/storage/whisper
    expose:
      - "80"
      - "2003"
  nginx:
    depends_on:
      - helloworld
    image: nginx:latest
    container_name: production_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 82:82
    links:
      - helloworld
      - graphite

volumes:
  graphite_data: {}
